worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # HTTP -> HTTPS
    server {
        listen 80;
        server_name currencyexchanger.duckdns.org;
        return 301 https://$host$request_uri;
    }

    # HTTPS для API и фронтенда
    server {
        listen 443 ssl http2;
        server_name currencyexchanger.duckdns.org;

        ssl_certificate /etc/letsencrypt/live/currencyexchanger.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/currencyexchanger.duckdns.org/privkey.pem;

        # фронтенд — статика из примонтированной папки client
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # API проксируем в backend-контейнер
        location ~ ^/(currencies|currency|exchangerates|exchangerate|scalar|openapi) {
            proxy_pass http://currencyexchanger:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}